"""edit product delete FK

Revision ID: 8e0beb402bfc
Revises: 526cc7431b6c
Create Date: 2023-12-13 05:10:29.557606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e0beb402bfc'
down_revision: Union[str, None] = '526cc7431b6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_provider_fkey', 'product', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('product_provider_fkey', 'product', 'provider', ['provider'], ['id'])
    # ### end Alembic commands ###
